version: 1.0.{build}
clone_depth: 1
test_script:
- ps: >-
    $scriptPath = Join-Path $env:APPVEYOR_BUILD_FOLDER -ChildPath "Test-Docs.ps1"
   
    & $scriptPath
    
    if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode) }
